#!/usr/bin/env bash
#Bash script that displays the content of the file /etc/passwd
while IFS=':' read -r username _ uid gid info home shell; do
    read -r _ _ _ _ _ _ passcode <<< "$info"
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell."
    echo "User ID's place is protected by the passcode $passcode, more info about the user here: $uid INFO"
    echo
done < /etc/passwd
