#!/usr/bin/env bash
#This script is displaying bad luck good luck and Best School
x=1
while [ $x -le 10 ]
do
    if [ $x -eq 4 ]
    then
        echo "Bad luck"
    elif [ $x -eq 8 ]
    then
        echo "Good luck"
    else
        echo "Best School"
    fi

    x=$((x+1))
done

