#!/usr/bin/env bash
#Counting from 1 to 20

x=1
while [ $x -le 20 ]
do
    case $x in
        4)
            echo "4"
            echo "Bad luck from China"
            ;;
        9)
            echo "9"
            echo "Bad luck from Japan"
            ;;
        17)
            echo "17"
            echo "Bad luck from Italy"
            ;;
        *)
            echo $x
            ;;
    esac

    x=$((x+1))
done

