#!/usr/bin/env bash
#Counting from 1 t0 20
counter=1

while [[ $counter -le 20 ]]
do
    case $counter in
        4)
            echo "4 and bad luck from China"
            ;;
        9)
            echo "9 and bad luck from Japan"
            ;;
        17)
            echo "17 and bad luck from Italy"
            ;;
        *)
            echo $counter
            ;;
    esac

    counter=$((counter + 1))
done
