#!/usr/bin/env bash

# Define the signal handlers
trap "echo 'I hate the kill command'" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT SIGTERM

# Create the PID file
echo $$ > /var/run/myscript.pid

# Display message indefinitely
while true
do
    echo "To infinity and beyond"
    sleep 1
done

